productblog/config/routes.rb
Rails.application.routes.draw do
  resources :lineitems
  resources :orders
  get 'addresses/create'

  get 'addresses/destroy'

  resources :users do
  member do
    get 'get_addresses'
  end
end

  get 'home/index'

  resources :categories
  resources :products

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

productblog/app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user

	has_many :orders
	#has_many :orders, through: => :users
end

productblog/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

productblog/app/models/lineitem.rb
class Lineitem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

productblog/app/models/order.rb
class Order < ApplicationRecord
	#has_one :address, through: => :users
	belongs_to :user

	belongs_to :address

	has_many :line_items
    #has_many :products, :through => :line_items

  #accepts_nested_attributes_for :line_items, :user , :address

  def user_attributes=(attrs)
    self.user = User.where(attrs).first_or_initialize(attrs) 
    @show_exists_message = !user.new_record?
  end


  def address_attributes=(attrs)
    self.address = Address.where(attrs).first_or_initialize(attrs) 
    @show_exists_message = !address.new_record?  
  end
end

productblog/app/models/product.rb
class Product < ApplicationRecord

	validates :name, presence: true

	  mount_uploader :image, ImageUploader


	has_many :lineitems
	# has_many :orders, through: => :lineitems


	validates_processing_of :image
validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end




	belongs_to :category, required: false
	attr_accessor :new_category_name
	
	before_save :create_category_from_name

  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end
  

  def self.search(search)
  where("name LIKE ? OR sku LIKE ?", "%#{search}%", "%#{search}%") 
end


end

productblog/app/models/user.rb
class User < ApplicationRecord

	#attr_accessor :address_attributes
	has_many :addresses, :dependent => :destroy
	has_many :orders
	accepts_nested_attributes_for :addresses, allow_destroy: true

	has_many :orders
end

productblog/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @li = @order.line_items
    @cust = @order.customer
    @add = @order.address

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  def new
          @users = User.all
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
                 @order.address.update_attributes(:customer_id => @order.customer_id)

        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_no, :tracking_no, :is_express_delivery, :is_customer_pickup, :dilivery_date, :order_currency, :special_instruction, :order_value, :user_id, :address_id)
    end
end

productblog/app/helpers/address_helper.rb
module AddressHelper
end

productblog/app/helpers/home_helper.rb
module HomeHelper
end

productblog/app/helpers/lineitems_helper.rb
module LineitemsHelper
end

productblog/app/helpers/orders_helper.rb
module OrdersHelper
end

productblog/app/helpers/products_helper.rb
module ProductsHelper
end

productblog/app/helpers/users_helper.rb
module UsersHelper
end

productblog/app/views/orders/_form.html.erb
<%= form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<script type="text/javascript">
//   $(document).ready(
//     function(){
//     addresses = $('#order_address_id')
//      $('#order_user_id').change(function(){
//       user = $('#order_user_id :selected').val();
//       var options = $(addresses).filter("optgroup[label='#{user}']").(html);
//       alert(addresses);
//      $('#order_address_id').html(options);

//   });

// });


  // var userData = JSON.parse(<%= @s.to_json %>);


// $(document).ready({
  
//   $('order_user_id').on('change', function() {
//   alert( this.value );
// });
//  //    function(){
 
//  //        var SELLERID = $("#seller_id_kit_import").val();
//  //        $.ajax({
//  //          url: "/admin/kits/load_market_places_for_bulk_kit_upload?seller_id="+SELLERID,
//  //          context: document.body
//  //        }).done(function(data) {
//  //        $("#product_bulk_import").html(data);
//  //        });
//  // });
// });

// $('#customer_id').on('change',function() {
//   alert( this.value );
// });
// $(document).ready({
$(document).on("change", '#customer_id', function() {
   // alert('DJ' );
   var user_id =  this.value;
   alert(user_id);
   $.ajax({
        url: "/users/"+user_id+"/get_addresses", //+SELLERID,
        type: "GET",
        dataType: "json",
        complete: function() {},
        success: function(data) { 
          alert(data);
          $('#address_id').

          $.each(data, function(addr){
            $('#address_id').append(
              //"<option value='"+addr['street']+ "'>"+addr['street']+"</option>"
              "<option value='asd'> jsd </option>"
              });
            
          })
          //$(".display_btw").html(data["street"]); 
        }
      });
  });
// });


</script>


<div class="row">
  <div class="field">
   <%= f.label :user_id %>
   <%= f.select :user_id, User.all.collect{|user| [user.first_name+" "+user.last_name, user.id]}, {:prompt => true}, {id: 'customer_id'} %>
 </div>

 <div class="field">
   <%= f.label :address_id %>
   <%= select_tag :address_id, options_for_select(['111', '222']), class: 'form-control', :include_blank => false, :required => false %>

   <%#= f.collection_select :address_id, User.order(:id), :addresses, :id, :id, :street, {:prompt => true}, { id: 'order_address_id'} %>
 </div>
</div>

<%= f.fields_for :address, @order.build_address do |address| %>
<div class="field">

  <%= address.label :line_1 %>
  <%= address.text_field :line_1 %>

  </div>
  <% end %>



  <!-- <div class="row">
            <div class="field">
              <%= f.label :user_id %>
              <%= f.select :user_id, User.all.collect { |user| [user.first_name + " " + user.last_name , user.id]}, {:prompt => true}, {id: 'order_user_id'}%>
            </div>
            <div class="field">
              <%= f.label :address_id %>
              <%= f.grouped_collection_select :address_id, User.order(:id), :addresses, :id, :id, :line_1, {:prompt => true}, { id: 'order_address_id'} %>
            </div>  
</div> -->

 <div class="form-group" >
      <h3>User Details</h3>
    
          <%= f.fields_for :user, @order.build_user do |builder| %>
            
              
                  <%= builder.label "Enter User Email Id :" %>
              
                          
                <%= builder.text_field :email, id: "input", :required => true %>
                
            

            
              
                <%= builder.label "First Name :" %>
              
              
                <%= builder.text_field :first_name, id: "first_name", :required => true %>
              
          

            
                <%= builder.label "Last Name :" %>
             
             
                  <%= builder.text_field :last_name, id: "last_name", :required => true %>
              

            
                <%= builder.label "Contact :" %>
             
                  <%= builder.text_field :contact, id: "contact", :required => true %>
              
            <% end %>
</div> 



<div class="form-group" >
      <h3>Address Details</h3>

            <%= f.fields_for :address, @order.build_address do |address| %>
            <div class="row">
                <div class="col-md-6">
                    <%= address.label "Shipping Address :" %>
                </div>
            </div>

            
                    <%= address.label :line_1 %>
                             
                    <%= address.text_field :line_1 , :required => true , id: 1%>
                
            
                    <%= address.label :line_2 %>
                
                     <%= address.text_field :line_2, :required => true, id: 2 %>
               
            
                  <%= address.label :street %>
                
                    <%= address.text_field :street, :required => true,id: 3%><br />
                
                  <%= address.label :city %>
                
                  <%= address.text_field :city , :required => true, id: 4%>
                
                    <%= address.label :state %>
                
                    <%= address.text_field :state, :required => true,id: 5 %><br />
                
                    <%= address.label :country %>
                
                    <%= address.text_field :country, :required => true,id: 5 %>
                
                    <%= address.label :postal_code %>
                
                    <%= address.text_field :postal_code, :required => true, id: 6 %>
                    <%#= f.text_field :customer_id, :required => true, id: 6 %>
                
            
             <div class="row">
                <div class="col-sm-6 col-sm-push-4" id="mylist"></div>
            </div>            
           <%end%>
          
    </div>



<div class="form-group" >
      <h3>Order Details</h3>
  <div class="form-group">
    <%= f.label :order_no, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :order_no, class: "form-control" %>
    </div>


  </div>
  <div class="form-group">
    <%= f.label :tracking_no, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tracking_no, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_express_delivery, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_express_delivery, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_customer_pickup, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_customer_pickup, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :dilivery_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :dilivery_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_currency, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :order_currency, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :special_instruction, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :special_instruction, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_value, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :order_value, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :address_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

productblog/app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing order</h1>
</div>

<%= render 'form' %>

productblog/app/views/orders/index.html.erb
<div class="page-header">
  <%= link_to new_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Order
  <% end %>
  <h1>Listing orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Order no</th>
            <th>Tracking no</th>
            <th>Is express delivery</th>
            <th>Is customer pickup</th>
            <th>Dilivery date</th>
            <th>Order currency</th>
            <th>Special instruction</th>
            <th>Order value</th>
            <th>User</th>
            <th>Address</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
            <td><%= order.order_no %></td>
            <td><%= order.tracking_no %></td>
            <td><%= order.is_express_delivery %></td>
            <td><%= order.is_customer_pickup %></td>
            <td><%= order.dilivery_date %></td>
            <td><%= order.order_currency %></td>
            <td><%= order.special_instruction %></td>
            <td><%= order.order_value %></td>
            <td><%= order.user_id %></td>
            <td><%= order.address_id %></td>
            <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

productblog/app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>

  

<%= form_for @order do |f| %>
   User: <%= f.collection_select :user_id, @users, :id, :first_name %>
   		Address: <%=  %>
   <%#= f.submit %>
<% end %>






  <h1>New order</h1>
</div>

<%= render 'form' %>

<%= form_tag(products_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
    <%= submit_tag "Search", :name => nil %>
<% end %><br /><br />

productblog/app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Order no:</dt>
  <dd><%= @order.order_no %></dd>

  <dt>Tracking no:</dt>
  <dd><%= @order.tracking_no %></dd>

  <dt>Is express delivery:</dt>
  <dd><%= @order.is_express_delivery %></dd>

  <dt>Is customer pickup:</dt>
  <dd><%= @order.is_customer_pickup %></dd>

  <dt>Dilivery date:</dt>
  <dd><%= @order.dilivery_date %></dd>

  <dt>Order currency:</dt>
  <dd><%= @order.order_currency %></dd>

  <dt>Special instruction:</dt>
  <dd><%= @order.special_instruction %></dd>

  <dt>Order value:</dt>
  <dd><%= @order.order_value %></dd>

  <dt>User:</dt>
  <dd><%= @order.user_id %></dd>

  <dt>Address:</dt>
  <dd><%= @order.address_id %></dd>

</dl>